global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    
  - job_name: 'fast_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['seyram.site'] 

  - job_name: 'ecs_exporter_fast_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['seyram.site:9779']

